### ISSUE TITLE
AI好像不好用？

### ISSUE THREAD

**Issue by scofieldle** [pcrbot/Salmon-plugin-transplant#1]
不管输什么命令，aichat都没有回复(包括关闭人工智障和调整AI概率)，也尝试了@和改sv的名字为aichat

**Comment by Watanabe-Asa** [comment]
文件夹名字改为aichat后再尝试一次，注意bot启动时是否导入了模块。

**Comment by scofieldle** [comment]
> 文件夹名字改为aichat后再尝试一次，注意bot启动时是否导入了模块。

昨天发现的时候就改了，因为bot模块里面直接写的aichat报错了。。

**Comment by Watanabe-Asa** [comment]
bot启动时有导入这个模块了吗。如果导入了，发送指令时的报错日志有吗。麻烦提供一下具体日志帮助判断。

**Comment by scofieldle** [comment]
我知道原因了，aichat是默认关闭服务的。。没有开启服务
