### ISSUE TITLE
搜图报错

### ISSUE THREAD

**Issue by yimo0908** [pcrbot/Salmon-plugin-transplant#2]
![image](https://user-images.githubusercontent.com/53830825/100303121-c801cc80-2fd6-11eb-9481-75f0d0d40df9.png)
已经安装了kth_timeoutdecorator包
其他hoshino插件也能正常使用

**Comment by Watanabe-Asa** [comment]
问题出在依赖kth_timeoutdecorator尚未适配python3.9版本。请尝试更新依赖kth_timeoutdecorator（pip install -U 依赖名）。若依然报错请等待依赖更新或者本插件对python3.9的适配。

**Comment by yimo0908** [comment]
感谢，我把python3.9换成3.8.6就能成功运行了
