### ISSUE TITLE
龙王插件图片路径不对

### ISSUE THREAD

**Issue by chajianku** [pcrbot/Salmon-plugin-transplant#5]
`[2021-01-22 22:52:25,894 hoshino] ERROR: 缺少图片资源：./res/img\res\img\longwang\QQ图片20210122223328.jpg`
res/img重复两次出现
![2021-01-22_225614](https://user-images.githubusercontent.com/16189313/105507073-b94d4280-5d05-11eb-99f2-06c9e1a8ccef.png)

**Comment by CCA2878** [comment]
如果你是在2021-1-15日之前clone的，现在再clone一次，资源路径这方面有更新。
如果不是的话，请检查你的HoshinoBot的RES_DIR路径配置是否正确。

**Comment by chajianku** [comment]
> 如果你是在2021-1-15日之前clone的，现在再clone一次，资源路径这方面有更新。
> 如果不是的话，请检查你的HoshinoBot的RES_DIR路径配置是否正确。

代码是17日的
填完整目录就能正确加载了，如果填缩写目录`RES_DIR = r'./res/'`就会报错

**Comment by CCA2878** [comment]
> > 如果你是在2021-1-15日之前clone的，现在再clone一次，资源路径这方面有更新。
> > 如果不是的话，请检查你的HoshinoBot的RES_DIR路径配置是否正确。
> 
> 代码是17日的
> 填完整目录就能正确加载了，如果填缩写目录`RES_DIR = r'./res/'`就会报错

那应该是Hoshino的R.py模块那边有bug……目前龙王插件读取资源都是用的这个模块内的类方法。

**Comment by CCA2878** [comment]
> `[2021-01-22 22:52:25,894 hoshino] ERROR: 缺少图片资源：./res/img\res\img\longwang\QQ图片20210122223328.jpg`
> res/img重复两次出现
> ![2021-01-22_225614](https://user-images.githubusercontent.com/16189313/105507073-b94d4280-5d05-11eb-99f2-06c9e1a8ccef.png)

而且很奇怪为什么在Linux环境内会出现Windows环境的反斜杠路径，longwang插件的路径目前都是给Hoshino自带模块处理的……

**Comment by chajianku** [comment]
> > `[2021-01-22 22:52:25,894 hoshino] ERROR: 缺少图片资源：./res/img\res\img\longwang\QQ图片20210122223328.jpg`
> > res/img重复两次出现
> > ![2021-01-22_225614](https://user-images.githubusercontent.com/16189313/105507073-b94d4280-5d05-11eb-99f2-06c9e1a8ccef.png)
> 
> 而且很奇怪为什么在Linux环境内会出现Windows环境的反斜杠路径，longwang插件的路径目前都是给Hoshino自带模块处理的……

啊这是windows下运行的，然后r'./res/' r'.\res' r'.\\res\\' 不管是正斜杠还是反斜杠都不行，必须填完整路径。
