### ISSUE TITLE
请问可以添加检测@机器人的功能吗

### ISSUE THREAD

**Issue by ganyunhan** [pcrbot/Salmon-plugin-transplant#6]
看了下源码，应该是@on_message没有only_to_me这个参数原因导致不太方便检测到@机器人，想问一下大佬目前有没有方法可以加上检测@的功能，这样就不会一直无脑在群里插嘴了hhhh

**Comment by Watanabe-Asa** [comment]
已优化。现在不会对at机器人的发言回复了。
