### ISSUE TITLE
请问可不可以提供一下原nonebot插件的源码链接QAQ

### ISSUE THREAD

**Issue by Jerry-FaGe** [pcrbot/Salmon-plugin-transplant#7]
您好，我是个新手nonebot2插件开发者，目前在找一些nonebot2的插件学习，看到这个项目感觉里面的插件都挺有趣的。请问这个移植之前的插件框架是nonebot还是nonebot2呢，可否提供一下原nonebot插件的源码链接，谢谢啦

**Comment by Watanabe-Asa** [comment]
移植的均为nonebot插件，原仓库均可以在文档底部的原作者的主页的公开仓库找到。
因为当时确实没认真注明来源，只是看到在意的就搬来，所以一个个对应会有点麻烦，非常不好意思（
